# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tistory updater

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # - cron: "0 0 */1 * *" # 매일
    - cron: "*/1 * * * *" # 1분마다

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
    - name: Update README
      run: |
        python main.py
    - name: Commit README
      run: |
        git add .
        git diff
        git config --local user.email "eun2ce@gihtub.com"
        git config --local user.name "eun2ce"
        git commit -m "docs: updated my tistory blog"
        git push
